### ISSUE TITLE
Iteration 2 submition

### ISSUE THREAD

**Issue by hodyama** [tamarke/Final_Project_Yeshiva#24]
https://github.com/tamarke/Final_Project_Yeshiva/wiki/ITR_2

**Comment by hadarp** [comment]
Please add a link to your application in Heroku, update readme file

**Comment by ayeletza** [comment]
Hi, we didn't upload our application on Heroku...
We did update our README file, and we checked it before sending.
We made it in Tmura so maybe some changes were not saved.
Now it updated.
