### ISSUE TITLE
Close iter-4 -summarize of project

### ISSUE THREAD

**Issue by ayeletza** [tamarke/Final_Project_Yeshiva#30]

**Comment by hadarp** [comment]
Where is the link to the page?

**Comment by ayeletza** [comment]
Hi,

We had a problem to load the final project to Heroku. As much we tried, we got this message in the end of the process:
You've reached the limit of 5 apps for unverified accounts. Delete some apps or add a credit card to verify your account.

This is the link to the site in Heroku. But it contains nothing...
https://dashboard.heroku.com/apps/yeshivaproject

So, we put a link to the final project that we loaded to GitHub.
This link:
https://github.com/tamarke/Final_Project_Yeshiva/tree/master/yedidOn

Thank you!!!
